import { IsString, IsNotEmpty, IsEnum, IsOptional, IsUUID } from 'class-validator';
import { MessageSender } from '../../../generated/prisma'; // Assuming MessageSender enum is generated by Prisma

export class AddMessageDto {
    @IsNotEmpty()
    @IsString()
    @IsUUID() // Ensure chatId is a valid UUID if your IDs are UUIDs, or CUID if CUIDs
    chatId: string;

    @IsNotEmpty()
    @IsString()
    content: string;

    @IsNotEmpty()
    @IsEnum(MessageSender)
    sender: MessageSender;

    @IsOptional()
    @IsString()
    extractedOcrText?: string;

    @IsOptional()
    @IsString()
    fileName?: string;
}